In [2]:
from typing import TypeVar


T = TypeVar('T')

def pr(val : T , title:str|None = None) : # type: ignore
    if title != None :
        print(f" ---------------------- {title} ---------------------- ")
    print('type: ' , type(val))
    print(val , '\n')
    # return val


In [4]:
import numpy as np # type: ignore

In [5]:
## Data types and attributes.
# Numpy main data type is ndarray
a1 = np.array([1,2,3,4,5,6,7,8,9])
pr(a1 , 'Our first numpy array')

 ---------------------- Our first numpy array ---------------------- 
type:  <class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8 9] 



In [8]:
# let's experiment wih n dimensional arrays
a2  = np.array([
    [1.0,2.0,3.2] , 
    [2.0,3.0,6.0]
])
pr(a2 , 'a2')
a3 = np.array([
    [[1, 2, 3],[4, 5, 6],[7, 8, 9]],
    [[10, 11, 12],[13, 14, 15],[16, 17, 18]]
    ])
pr(a3 , 'a3')

 ---------------------- a2 ---------------------- 
type:  <class 'numpy.ndarray'>
[[1.  2.  3.2]
 [2.  3.  6. ]] 

 ---------------------- a3 ---------------------- 
type:  <class 'numpy.ndarray'>
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]] 



In [9]:
pr(a1.shape , 'a1.shape')
pr(a2.shape , 'a2.shape')
pr(a3.shape , 'a3.shape')

 ---------------------- a1.shape ---------------------- 
type:  <class 'tuple'>
(9,) 

 ---------------------- a2.shape ---------------------- 
type:  <class 'tuple'>
(2, 3) 

 ---------------------- a3.shape ---------------------- 
type:  <class 'tuple'>
(2, 3, 3) 



In [10]:
pr(a1.ndim , 'a1.ndim')
pr(a2.ndim , 'a2.ndim')
pr(a3.ndim , 'a3.ndim')


 ---------------------- a1.ndim ---------------------- 
type:  <class 'int'>
1 

 ---------------------- a2.ndim ---------------------- 
type:  <class 'int'>
2 

 ---------------------- a3.ndim ---------------------- 
type:  <class 'int'>
3 



In [11]:
pr(a1.dtype , 'a1.dtype')
pr(a2.dtype , 'a2.dtype')
pr(a3.dtype , 'a3.dtype')


 ---------------------- a1.dtype ---------------------- 
type:  <class 'numpy.dtypes.Int64DType'>
int64 

 ---------------------- a2.dtype ---------------------- 
type:  <class 'numpy.dtypes.Float64DType'>
float64 

 ---------------------- a3.dtype ---------------------- 
type:  <class 'numpy.dtypes.Int64DType'>
int64 



In [12]:
pr(a1.size , 'a1.size')
pr(a2.size , 'a2.size')
pr(a3.size , 'a3.size')


 ---------------------- a1.size ---------------------- 
type:  <class 'int'>
9 

 ---------------------- a2.size ---------------------- 
type:  <class 'int'>
6 

 ---------------------- a3.size ---------------------- 
type:  <class 'int'>
18 



In [13]:
pr(type(a1) , 'type(a1)')
pr(type(a2) , 'type(a2)')
pr(type(a3) , 'type(a3)')


 ---------------------- type(a1) ---------------------- 
type:  <class 'type'>
<class 'numpy.ndarray'> 

 ---------------------- type(a2) ---------------------- 
type:  <class 'type'>
<class 'numpy.ndarray'> 

 ---------------------- type(a3) ---------------------- 
type:  <class 'type'>
<class 'numpy.ndarray'> 



In [15]:
# Create a data frame from a numpy
import pandas as pd
df2 = pd.DataFrame(a2)
pr(df2)

type:  <class 'pandas.core.frame.DataFrame'>
     0    1    2
0  1.0  2.0  3.2
1  2.0  3.0  6.0 



In [ ]:
# if the numpy array that have more than three dimensions. you can't make it a pandas dataframe like what i did in above because it will throw an error `ValueError: Must pass 2-d input. shape=(2, 3, 3)`
df3 = pd.DataFrame(a3)
pr(df3)

ValueError: Must pass 2-d input. shape=(2, 3, 3)