In [ ]:
from typing import TypeVar


T = TypeVar('T')

def pr(val : T , title:str|None = None) : # type: ignore
    if title != None :
        print(f" ---------------------- {title} ---------------------- ")
    print('type: ' , type(val))
    print(val , '\n')
    # return val


In [18]:
import numpy as np # type: ignore
import numpy.typing as npt # type: ignore

In [19]:
ones : npt.NDArray[np.float64] = np.ones((2,3))
pr(ones , 'ones')
zeros :npt.NDArray[np.float64] = np.zeros((2,3))
pr(zeros , 'zeros')
sevens: npt.NDArray[np.int64] = np.full(shape=(5,3) , fill_value= 7)
pr(sevens , 'sevens')

 ---------------------- ones ---------------------- 
type:  <class 'numpy.ndarray'>
[[1. 1. 1.]
 [1. 1. 1.]] 

 ---------------------- zeros ---------------------- 
type:  <class 'numpy.ndarray'>
[[0. 0. 0.]
 [0. 0. 0.]] 

 ---------------------- sevens ---------------------- 
type:  <class 'numpy.ndarray'>
[[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]] 



In [7]:
arange = np.arange(0 , 10 , 2)
pr(arange , 'arange' )

 ---------------------- arange ---------------------- 
type:  <class 'numpy.ndarray'>
[0 2 4 6 8] 



In [8]:
rarray = np.random.randint(low=0 , high=10 , size=(3,3))
pr(rarray , 'rarray')

 ---------------------- rarray ---------------------- 
type:  <class 'numpy.ndarray'>
[[2 8 4]
 [9 9 2]
 [2 3 1]] 



In [15]:
rarray = (np.random.random(size=(5,3))*100).round()

pr(rarray , 'rarray')
pr(rarray.shape , 'rarray.shape')


 ---------------------- rarray ---------------------- 
type:  <class 'numpy.ndarray'>
[[ 6. 94.  7.]
 [81. 42. 52.]
 [81. 10. 90.]
 [39. 42. 13.]
 [15.  4. 19.]] 

 ---------------------- rarray.shape ---------------------- 
type:  <class 'tuple'>
(5, 3) 



In [16]:
rarray = np.random.rand(5,3)
pr(rarray , 'rarray')

 ---------------------- rarray ---------------------- 
type:  <class 'numpy.ndarray'>
[[0.77696353 0.03345785 0.85089955]
 [0.63870817 0.12045367 0.57159005]
 [0.41179198 0.56085724 0.86169209]
 [0.70444942 0.05893079 0.94342712]
 [0.42928213 0.1681253  0.91177075]] 



In [ ]:
evens : npt.NDArray[np.int64] = np.arange(start=0 , stop=10 , step=2 , dtype=np.int64)
pr(evens , 'evens')

type:  <class 'numpy.ndarray'>
[0 2 4 6 8] 

