In [1]:
from typing import TypeVar


T = TypeVar('T')

def pr(val : T , title:str|None = None) : # type: ignore
    if title != None :
        print(f" ---------------------- {title} ---------------------- ")
    print('type: ' , type(val))
    print(val , '\n')
    # return val


In [2]:
import numpy as np # type: ignore
import numpy.typing as npt # type: ignore

In [ ]:
np.random.seed(seed=0)
rarray : npt.NDArray[np.int64] = np.random.randint(low=0 , high=10 , dtype=np.int64 , size=(5,3) )
pr(rarray ,  'rarray')

 ---------------------- rarray ---------------------- 
type:  <class 'numpy.ndarray'>
[[5 0 3]
 [3 7 9]
 [3 5 2]
 [4 7 6]
 [8 8 1]] 



In [13]:
np.random.seed(7)
rarray = np.random.random(size=(5,3))
pr(rarray , 'rarray')

 ---------------------- rarray ---------------------- 
type:  <class 'numpy.ndarray'>
[[0.07630829 0.77991879 0.43840923]
 [0.72346518 0.97798951 0.53849587]
 [0.50112046 0.07205113 0.26843898]
 [0.4998825  0.67923    0.80373904]
 [0.38094113 0.06593635 0.2881456 ]] 

