In [1]:
from typing import TypeVar


T = TypeVar('T')

def pr(val : T , title:str|None = None) : # type: ignore
    if title != None :
        print(f" ---------------------- {title} ---------------------- ")
    print('type: ' , type(val))
    print(val , '\n')
    # return val


In [2]:
import numpy as np # type: ignore
import numpy.typing as npt # type: ignore

In [15]:
rarray : npt.NDArray[np.int64] = np.random.randint(low=0 , high=10 ,  size=(3,4,5))
pr(rarray, 'rarray')

 ---------------------- rarray ---------------------- 
type:  <class 'numpy.ndarray'>
[[[3 5 8 1 4]
  [2 4 3 4 8]
  [2 8 7 0 4]
  [6 1 7 2 6]]

 [[2 0 1 9 5]
  [3 8 7 5 5]
  [8 5 9 0 4]
  [6 7 8 6 5]]

 [[8 9 5 4 7]
  [8 2 5 3 0]
  [6 1 0 5 3]
  [2 4 5 8 8]]] 



In [17]:
rng: np.random.Generator = np.random.default_rng(seed=7)
a :npt.NDArray[np.int64] = rng.integers(0,10 , size=(3,4,5))
pr(a , 'array of unique integers')
unique  = np.unique(a)
pr(unique , 'list of all unique value in the array')

 ---------------------- array of unique integers ---------------------- 
type:  <class 'numpy.ndarray'>
[[[9 6 6 8 5]
  [7 8 2 0 3]
  [2 8 9 0 4]
  [8 1 7 1 4]]

 [[8 3 3 2 7]
  [2 9 4 4 5]
  [5 5 5 9 8]
  [7 7 6 3 9]]

 [[4 2 8 1 8]
  [6 1 0 4 0]
  [1 5 9 4 8]
  [9 8 6 4 5]]] 

 ---------------------- list of all unique value in the array ---------------------- 
type:  <class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9] 



In [ ]:
# get the unique elements in an array 
unique: npt.NDArray[np.int64] = np.unique(rarray)
pr(unique)

type:  <class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9] 



In [9]:
# let's experiment with indexing in numpy. 
# i created an array that have the size of (3,4,5)
pr(rarray , 'rarray')
pr(rarray[0] , 'rarray[0]')
pr(rarray[0][0] , 'rarray[0][0]')
pr(rarray[0][0][0] , 'rarray[0][0][0]')

 ---------------------- rarray ---------------------- 
type:  <class 'numpy.ndarray'>
[[[1 5 5 6 1]
  [4 8 9 3 2]
  [3 3 4 3 9]
  [6 0 0 8 8]]

 [[2 6 3 7 0]
  [0 6 5 7 3]
  [9 0 4 3 6]
  [3 3 9 8 1]]

 [[6 8 3 4 1]
  [4 1 5 3 2]
  [5 8 3 6 5]
  [0 7 7 2 1]]] 

 ---------------------- rarray[0] ---------------------- 
type:  <class 'numpy.ndarray'>
[[1 5 5 6 1]
 [4 8 9 3 2]
 [3 3 4 3 9]
 [6 0 0 8 8]] 

 ---------------------- rarray[0][0] ---------------------- 
type:  <class 'numpy.ndarray'>
[1 5 5 6 1] 

 ---------------------- rarray[0][0][0] ---------------------- 
type:  <class 'numpy.int32'>
1 



In [10]:
# let's experiment with indexing in numpy. 
# i created an array that have the size of (3,4,5)
pr(rarray , 'rarray')
pr(rarray[2] , 'rarray[2]')
pr(rarray[2][2] , 'rarray[2][2]')
pr(rarray[2][2][2] , 'rarray[2][2][2]')

 ---------------------- rarray ---------------------- 
type:  <class 'numpy.ndarray'>
[[[1 5 5 6 1]
  [4 8 9 3 2]
  [3 3 4 3 9]
  [6 0 0 8 8]]

 [[2 6 3 7 0]
  [0 6 5 7 3]
  [9 0 4 3 6]
  [3 3 9 8 1]]

 [[6 8 3 4 1]
  [4 1 5 3 2]
  [5 8 3 6 5]
  [0 7 7 2 1]]] 

 ---------------------- rarray[2] ---------------------- 
type:  <class 'numpy.ndarray'>
[[6 8 3 4 1]
 [4 1 5 3 2]
 [5 8 3 6 5]
 [0 7 7 2 1]] 

 ---------------------- rarray[2][2] ---------------------- 
type:  <class 'numpy.ndarray'>
[5 8 3 6 5] 

 ---------------------- rarray[2][2][2] ---------------------- 
type:  <class 'numpy.int32'>
3 



In [13]:
# let's experiment with indexing in numpy. 
# i created an array that have the size of (3,4,5)
pr(rarray , 'rarray')
pr(rarray[:2] , 'rarray[:2]')
pr(rarray[:2][:2] , 'rarray[:2][:2]')
pr(rarray[:2][:2][:2] , 'rarray[:2][:2][:2]')

 ---------------------- rarray ---------------------- 
type:  <class 'numpy.ndarray'>
[[[1 5 5 6 1]
  [4 8 9 3 2]
  [3 3 4 3 9]
  [6 0 0 8 8]]

 [[2 6 3 7 0]
  [0 6 5 7 3]
  [9 0 4 3 6]
  [3 3 9 8 1]]

 [[6 8 3 4 1]
  [4 1 5 3 2]
  [5 8 3 6 5]
  [0 7 7 2 1]]] 

 ---------------------- rarray[:2] ---------------------- 
type:  <class 'numpy.ndarray'>
[[[1 5 5 6 1]
  [4 8 9 3 2]
  [3 3 4 3 9]
  [6 0 0 8 8]]

 [[2 6 3 7 0]
  [0 6 5 7 3]
  [9 0 4 3 6]
  [3 3 9 8 1]]] 

 ---------------------- rarray[:2][:2] ---------------------- 
type:  <class 'numpy.ndarray'>
[[[1 5 5 6 1]
  [4 8 9 3 2]
  [3 3 4 3 9]
  [6 0 0 8 8]]

 [[2 6 3 7 0]
  [0 6 5 7 3]
  [9 0 4 3 6]
  [3 3 9 8 1]]] 

 ---------------------- rarray[:2][:2][:2] ---------------------- 
type:  <class 'numpy.ndarray'>
[[[1 5 5 6 1]
  [4 8 9 3 2]
  [3 3 4 3 9]
  [6 0 0 8 8]]

 [[2 6 3 7 0]
  [0 6 5 7 3]
  [9 0 4 3 6]
  [3 3 9 8 1]]] 



In [14]:
# let's experiment with indexing in numpy. 
# i created an array that have the size of (3,4,5)
pr(rarray , 'rarray')
pr(rarray[:2] , 'rarray[:2]')
pr(rarray[:2,:2] , 'rarray[:2 , :2]')
pr(rarray[:2 ,:2 ,:2] , 'rarray[:2 , :2 ,:2]')

 ---------------------- rarray ---------------------- 
type:  <class 'numpy.ndarray'>
[[[1 5 5 6 1]
  [4 8 9 3 2]
  [3 3 4 3 9]
  [6 0 0 8 8]]

 [[2 6 3 7 0]
  [0 6 5 7 3]
  [9 0 4 3 6]
  [3 3 9 8 1]]

 [[6 8 3 4 1]
  [4 1 5 3 2]
  [5 8 3 6 5]
  [0 7 7 2 1]]] 

 ---------------------- rarray[:2] ---------------------- 
type:  <class 'numpy.ndarray'>
[[[1 5 5 6 1]
  [4 8 9 3 2]
  [3 3 4 3 9]
  [6 0 0 8 8]]

 [[2 6 3 7 0]
  [0 6 5 7 3]
  [9 0 4 3 6]
  [3 3 9 8 1]]] 

 ---------------------- rarray[:2 , :2] ---------------------- 
type:  <class 'numpy.ndarray'>
[[[1 5 5 6 1]
  [4 8 9 3 2]]

 [[2 6 3 7 0]
  [0 6 5 7 3]]] 

 ---------------------- rarray[:2 , :2 ,:2] ---------------------- 
type:  <class 'numpy.ndarray'>
[[[1 5]
  [4 8]]

 [[2 6]
  [0 6]]] 

