In [1]:
from typing import TypeVar


T = TypeVar('T')

def pr(val : T , title:str|None = None) : # type: ignore
    if title != None :
        print(f" ---------------------- {title} ---------------------- ")
    print('type: ' , type(val))
    print(val , '\n')
    # return val


In [2]:
import numpy as np # type: ignore
import numpy.typing as npt # type: ignore

In [3]:
a1 : npt.NDArray [np.int64] = np.array([1,2,3])
ones = np.ones(shape=(3))
pr(a1 , 'a1')
pr(ones , 'ones')
pr(a1 + ones , 'a2 + ones')
pr(a1 - ones , 'a2 - ones')
pr(a1 * ones , 'a1 * ones' )

 ---------------------- a1 ---------------------- 
type:  <class 'numpy.ndarray'>
[1 2 3] 

 ---------------------- ones ---------------------- 
type:  <class 'numpy.ndarray'>
[1. 1. 1.] 

 ---------------------- a2 + ones ---------------------- 
type:  <class 'numpy.ndarray'>
[2. 3. 4.] 

 ---------------------- a2 - ones ---------------------- 
type:  <class 'numpy.ndarray'>
[0. 1. 2.] 

 ---------------------- a1 * ones ---------------------- 
type:  <class 'numpy.ndarray'>
[1. 2. 3.] 



In [7]:
a2 = np.random.randint(1,10 , size=(3,3))
a3 = np.random.randint(1,10 , size=(3,3))
pr(a1 , 'a1')
pr(a2 , 'a2')
pr(a1 * a2 , 'a1 * a2')
pr(a3 / a2 , 'a3 / a2')
pr(a3 // a2 , 'a3 // a2') 
pr(a2 ** 2 , 'a2 ** 2')
pr(a2 % 2 , 'a2 % 2')


 ---------------------- a1 ---------------------- 
type:  <class 'numpy.ndarray'>
[1 2 3] 

 ---------------------- a2 ---------------------- 
type:  <class 'numpy.ndarray'>
[[9 7 7]
 [7 9 1]
 [5 6 4]] 

 ---------------------- a1 * a2 ---------------------- 
type:  <class 'numpy.ndarray'>
[[ 9 14 21]
 [ 7 18  3]
 [ 5 12 12]] 

 ---------------------- a3 / a2 ---------------------- 
type:  <class 'numpy.ndarray'>
[[0.66666667 0.14285714 0.14285714]
 [1.14285714 0.11111111 6.        ]
 [1.2        1.5        2.25      ]] 

 ---------------------- a3 // a2 ---------------------- 
type:  <class 'numpy.ndarray'>
[[0 0 0]
 [1 0 6]
 [1 1 2]] 

 ---------------------- a2 ** 2 ---------------------- 
type:  <class 'numpy.ndarray'>
[[81 49 49]
 [49 81  1]
 [25 36 16]] 

 ---------------------- a2 % 2 ---------------------- 
type:  <class 'numpy.ndarray'>
[[1 1 1]
 [1 1 1]
 [1 0 0]] 

