In [1]:
from typing import TypeVar


T = TypeVar('T')

def pr(val : T , title:str|None = None) : # type: ignore
    if title != None :
        print(f" ---------------------- {title} ---------------------- ")
    print('type: ' , type(val))
    print(val , '\n')
    # return val


In [2]:
import numpy as np # type: ignore
import numpy.typing as npt # type: ignore

In [13]:


x = np.array([[0,1,2],
             [3,4,5],
             [6,7,8]])
y = np.array([[1],[10],[100]])
pr(x , 'x')
pr(y , 'y')
shape= (3,3)
output = np.empty(shape , int)
n0  , n1 = shape
for i in range(n0):
    for k in range(n1):
        output[i , k] = x[i , k] + y[i , 0] 
        print(f"i: {i} | k: {k}\noutput[{i},{k}]: {output[i,k]} | x[{i} , {k}]: {x[i , k]} |  y[{i} , 0]: { y[i , 0] }")
pr(output , 'output')
pr(x+y , 'x+y')

 ---------------------- x ---------------------- 
type:  <class 'numpy.ndarray'>
[[0 1 2]
 [3 4 5]
 [6 7 8]] 

 ---------------------- y ---------------------- 
type:  <class 'numpy.ndarray'>
[[  1]
 [ 10]
 [100]] 

i: 0 | k: 0
output[0,0]: 1 | x[0 , 0]: 0 |  y[0 , 0]: 1
i: 0 | k: 1
output[0,1]: 2 | x[0 , 1]: 1 |  y[0 , 0]: 1
i: 0 | k: 2
output[0,2]: 3 | x[0 , 2]: 2 |  y[0 , 0]: 1
i: 1 | k: 0
output[1,0]: 13 | x[1 , 0]: 3 |  y[1 , 0]: 10
i: 1 | k: 1
output[1,1]: 14 | x[1 , 1]: 4 |  y[1 , 0]: 10
i: 1 | k: 2
output[1,2]: 15 | x[1 , 2]: 5 |  y[1 , 0]: 10
i: 2 | k: 0
output[2,0]: 106 | x[2 , 0]: 6 |  y[2 , 0]: 100
i: 2 | k: 1
output[2,1]: 107 | x[2 , 1]: 7 |  y[2 , 0]: 100
i: 2 | k: 2
output[2,2]: 108 | x[2 , 2]: 8 |  y[2 , 0]: 100
 ---------------------- output ---------------------- 
type:  <class 'numpy.ndarray'>
[[  1   2   3]
 [ 13  14  15]
 [106 107 108]] 

 ---------------------- x+y ---------------------- 
type:  <class 'numpy.ndarray'>
[[  1   2   3]
 [ 13  14  15]
 [106 107 108]]

In [20]:
x = np.array([
    [
     [0,1,2] , [3,4,5] , [6,7,8]   
    ] ,[
     [9,10,11] , [12,13,14] , [15,16,17]   
    ] ,
])
y = np.array([1,10,100]) 
pr(x , 'x')
pr(x.shape , 'x.shape')
pr(y , 'y')
pr(y.shape , 'y.shape')
shape = (2,3,3)
n0 , n1 , n2 = shape
output = np.empty(shape=shape , dtype=int)
for i in range(n0):
    for j in range(n1) :
        for k in range(n2) :
            output[i , j , k] = x[i , j , k] + y[ k]
            print(f"i: {i} | j: {j} | k: {k}\noutput[{i} , {j} , {k}]: {output[i , j , k]} |  x[{i} , {j} , {k}]: { x[i , j , k]} |  y[{k}]: { y[ k]}")
pr(output , 'output')
pr(x+y , 'x+y')
            
            

 ---------------------- x ---------------------- 
type:  <class 'numpy.ndarray'>
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]] 

 ---------------------- x.shape ---------------------- 
type:  <class 'tuple'>
(2, 3, 3) 

 ---------------------- y ---------------------- 
type:  <class 'numpy.ndarray'>
[  1  10 100] 

 ---------------------- y.shape ---------------------- 
type:  <class 'tuple'>
(3,) 

i: 0 | j: 0 | k: 0
output[0 , 0 , 0]: 1 |  x[0 , 0 , 0]: 0 |  y[0]: 1
i: 0 | j: 0 | k: 1
output[0 , 0 , 1]: 11 |  x[0 , 0 , 1]: 1 |  y[1]: 10
i: 0 | j: 0 | k: 2
output[0 , 0 , 2]: 102 |  x[0 , 0 , 2]: 2 |  y[2]: 100
i: 0 | j: 1 | k: 0
output[0 , 1 , 0]: 4 |  x[0 , 1 , 0]: 3 |  y[0]: 1
i: 0 | j: 1 | k: 1
output[0 , 1 , 1]: 14 |  x[0 , 1 , 1]: 4 |  y[1]: 10
i: 0 | j: 1 | k: 2
output[0 , 1 , 2]: 105 |  x[0 , 1 , 2]: 5 |  y[2]: 100
i: 0 | j: 2 | k: 0
output[0 , 2 , 0]: 7 |  x[0 , 2 , 0]: 6 |  y[0]: 1
i: 0 | j: 2 | k: 1
output[0 , 2 , 1]: 17 |  x[0 , 2 , 1]: 7