In [1]:
from typing import TypeVar


T = TypeVar('T')

def pr(val : T , title:str|None = None) : # type: ignore
    if title != None :
        print(f" ---------------------- {title} ---------------------- ")
    print('type: ' , type(val))
    print(val , '\n')
    # return val


In [2]:
import numpy as np # type: ignore
import numpy.typing as npt # type: ignore

In [3]:
ones  = np.ones((5))
pr(ones.sum() , 'sum')

 ---------------------- sum ---------------------- 
type:  <class 'numpy.float64'>
5.0 



In [6]:
massive_array = np.random.randint(low=0 , high=1000 , size=(100000))
%timeit sum(massive_array)
%timeit massive_array.sum()

6.95 ms ± 323 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
72.6 μs ± 4.42 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [7]:
np.random.seed(42)
a2:npt.NDArray[np.int64] = np.random.randint(low=1 , high=10 , size=(3,3))
pr(a2 , 'a2')
pr(a2.sum() , 'a2.sum()')
pr(a2.mean() , 'a2.mean()')
pr(a2.max() , 'a2.max()')
pr(a2.std() , 'a2.std()')
pr(a2.var() , 'a2.var()')

 ---------------------- a2 ---------------------- 
type:  <class 'numpy.ndarray'>
[[7 4 8]
 [5 7 3]
 [7 8 5]] 

 ---------------------- a2.sum() ---------------------- 
type:  <class 'numpy.int64'>
54 

 ---------------------- a2.mean() ---------------------- 
type:  <class 'numpy.float64'>
6.0 

 ---------------------- a2.max() ---------------------- 
type:  <class 'numpy.int32'>
8 

 ---------------------- a2.std() ---------------------- 
type:  <class 'numpy.float64'>
1.699673171197595 

 ---------------------- a2.var() ---------------------- 
type:  <class 'numpy.float64'>
2.888888888888889 

