In [1]:
from typing import TypeVar


T = TypeVar('T')

def pr(val : T , title:str|None = None) : # type: ignore
    if title != None :
        print(f" ---------------------- {title} ---------------------- ")
    print('type: ' , type(val))
    print(val , '\n')
    # return val


In [2]:
import numpy as np # type: ignore
import numpy.typing as npt # type: ignore

In [5]:
arr1 =  np.random.randint(0 , 10 , size=(2,3))
arr2 =  np.random.randint(0 , 10 , size=(2,3 , 3))
pr(arr1 , 'arr1')
pr(arr1.shape , 'arr1.shape')
pr(arr2 , 'arr2')
pr(arr2.shape , 'arr2.shape')

 ---------------------- arr1 ---------------------- 
type:  <class 'numpy.ndarray'>
[[1 7 8]
 [4 5 7]] 

 ---------------------- arr1.shape ---------------------- 
type:  <class 'tuple'>
(2, 3) 

 ---------------------- arr2 ---------------------- 
type:  <class 'numpy.ndarray'>
[[[5 3 3]
  [8 3 6]
  [8 8 9]]

 [[6 2 3]
  [4 6 6]
  [4 9 1]]] 

 ---------------------- arr2.shape ---------------------- 
type:  <class 'tuple'>
(2, 3, 3) 



In [ ]:
pr(arr1 , 'arr1')
arr1_reshape = arr1.reshape((2,3,1))
pr( arr1_reshape, 'arr1.reshape((2,3,1))')
pr(arr2 , 'arr2')
pr(arr1_reshape * arr2 , 'now multiplication is possible because shapes is compatible.')

 ---------------------- arr1 ---------------------- 
type:  <class 'numpy.ndarray'>
[[1 7 8]
 [4 5 7]] 

 ---------------------- arr1.reshape((2,3,1)) ---------------------- 
type:  <class 'numpy.ndarray'>
[[[1]
  [7]
  [8]]

 [[4]
  [5]
  [7]]] 

 ---------------------- arr2 ---------------------- 
type:  <class 'numpy.ndarray'>
[[[5 3 3]
  [8 3 6]
  [8 8 9]]

 [[6 2 3]
  [4 6 6]
  [4 9 1]]] 

type:  <class 'numpy.ndarray'>
[[[ 5  3  3]
  [56 21 42]
  [64 64 72]]

 [[24  8 12]
  [20 30 30]
  [28 63  7]]] 



In [12]:
# transpose is switching the axes
pr(arr1 , 'arr1')
pr(arr1.T , 'arr1.T')

 ---------------------- arr1 ---------------------- 
type:  <class 'numpy.ndarray'>
[[1 7 8]
 [4 5 7]] 

 ---------------------- arr1.T ---------------------- 
type:  <class 'numpy.ndarray'>
[[1 4]
 [7 5]
 [8 7]] 

