In [1]:
from typing import TypeVar


T = TypeVar('T')

def pr(val : T , title:str|None = None) : # type: ignore
    if title != None :
        print(f" ---------------------- {title} ---------------------- ")
    print('type: ' , type(val))
    print(val , '\n')
    # return val


In [2]:
import numpy as np # type: ignore
import numpy.typing as npt # type: ignore

In [5]:
np.random.seed(0)
mt1 = np.random.randint(0,10,(5,3))
mt2 = np.random.randint(0,10,(5,3))
pr(mt1 , 'mt1')
pr(mt2 , 'mt2')

 ---------------------- mt1 ---------------------- 
type:  <class 'numpy.ndarray'>
[[5 0 3]
 [3 7 9]
 [3 5 2]
 [4 7 6]
 [8 8 1]] 

 ---------------------- mt2 ---------------------- 
type:  <class 'numpy.ndarray'>
[[6 7 7]
 [8 1 5]
 [9 8 9]
 [4 3 0]
 [3 5 0]] 



In [ ]:
# what we studied so far is element-wise multiplication.
pr(mt1*mt2 , 'mt1*mt2')

 ---------------------- mt1*mt2 ---------------------- 
type:  <class 'numpy.ndarray'>
[[30  0 21]
 [24  7 45]
 [27 40 18]
 [16 21  0]
 [24 40  0]] 



In [ ]:
# let's try to perform dot product
# the code below will produce an error that the size don't match
# the error that will show up when running the below code is `ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)`
np.dot(mt1,mt2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [ ]:
# you have to perform a transpose so dot multiplication don't produce an error.
# can you make sense of what dot product do. not the math but i want to make sense why we use dot product in simple terms and beginner friendly way.
pr(np.dot(mt1,mt2.T))


type:  <class 'numpy.ndarray'>
[[ 51  55  72  20  15]
 [130  76 164  33  44]
 [ 67  39  85  27  34]
 [115  69 146  37  47]
 [111  77 145  56  64]] 

