In [1]:
from typing import TypeVar


T = TypeVar('T')

def pr(val : T , title:str|None = None) : # type: ignore
    if title != None :
        print(f" ---------------------- {title} ---------------------- ")
    print('type: ' , type(val))
    print(val , '\n')
    # return val


In [5]:
import numpy as np # type: ignore
import numpy.typing as npt # type: ignore
import pandas as pd

In [3]:
np.random.seed(0)
sales_amount = np.random.randint(10,20 , (5,3))
pr(sales_amount , 'sales_amount')

 ---------------------- sales_amount ---------------------- 
type:  <class 'numpy.ndarray'>
[[15 10 13]
 [13 17 19]
 [13 15 12]
 [14 17 16]
 [18 18 11]] 



In [10]:
weekly_sales = pd.DataFrame(
    sales_amount , 
    index=['Mon' , 'Tues' ,'Wed' , 'Thurs' , 'Fri' ],
    columns=['Almond Butter' , 'Peanut Butter' , 'Cashew Butter']
    )
pr(weekly_sales , 'weekly_sales')

 ---------------------- weekly_sales ---------------------- 
type:  <class 'pandas.core.frame.DataFrame'>
       Almond Butter  Peanut Butter  Cashew Butter
Mon               15             10             13
Tues              13             17             19
Wed               13             15             12
Thurs             14             17             16
Fri               18             18             11 



In [22]:
prices = np.array([10,8,12])
pr(prices , 'prices')
prices = prices.reshape((1,3))
pr(prices , 'prices')
butter_prices = pd.DataFrame(
    prices , 
    index=['Price'] ,
    columns=['Almond Butter' , 'Peanut Butter' , 'Cashew Butter']
    )
pr(butter_prices , 'butter_prices')

 ---------------------- prices ---------------------- 
type:  <class 'numpy.ndarray'>
[10  8 12] 

 ---------------------- prices ---------------------- 
type:  <class 'numpy.ndarray'>
[[10  8 12]] 

 ---------------------- butter_prices ---------------------- 
type:  <class 'pandas.core.frame.DataFrame'>
       Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12 



In [25]:
total_sales = sales_amount.dot(prices.T)
pr(total_sales , 'total_sales')

 ---------------------- total_sales ---------------------- 
type:  <class 'numpy.ndarray'>
[[386]
 [494]
 [394]
 [468]
 [456]] 



In [29]:
pr(butter_prices , 'butter_prices')
weekly_sales['Total ($)'] = total_sales 
pr(weekly_sales , 'weekly_sales')

 ---------------------- butter_prices ---------------------- 
type:  <class 'pandas.core.frame.DataFrame'>
       Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12 

 ---------------------- weekly_sales ---------------------- 
type:  <class 'pandas.core.frame.DataFrame'>
       Almond Butter  Peanut Butter  Cashew Butter  Total ($)
Mon               15             10             13        386
Tues              13             17             19        494
Wed               13             15             12        394
Thurs             14             17             16        468
Fri               18             18             11        456 

