In [1]:
from typing import TypeVar


T = TypeVar('T')

def pr(val : T , title:str|None = None) : # type: ignore
    if title != None :
        print(f" ---------------------- {title} ---------------------- ")
    print('type: ' , type(val))
    print(val , '\n')
    # return val


In [2]:
import numpy as np # type: ignore
import numpy.typing as npt # type: ignore
import pandas as pd # type: ignore

In [3]:
a1 : npt.NDArray[np.int64] = np.random.randint(10,20, (3))
a2 : npt.NDArray[np.int64] = np.random.randint(10,20, (2,3))
pr(a1 , 'a1')
pr(a2 , 'a2')

 ---------------------- a1 ---------------------- 
type:  <class 'numpy.ndarray'>
[16 15 12] 

 ---------------------- a2 ---------------------- 
type:  <class 'numpy.ndarray'>
[[13 18 12]
 [17 12 15]] 



In [7]:
bool_array :npt.NDArray[np.bool] = a1 > a2
pr(bool_array , 'a1 > a2')
bool_array :npt.NDArray[np.bool] = a1 < a2
pr(bool_array , 'a1 < a2')
bool_array :npt.NDArray[np.bool] = a1 == a2
pr(bool_array , 'a1 == a2')

 ---------------------- a1 > a2 ---------------------- 
type:  <class 'numpy.ndarray'>
[[ True False False]
 [False  True False]] 

 ---------------------- a1 < a2 ---------------------- 
type:  <class 'numpy.ndarray'>
[[False  True False]
 [ True False  True]] 

 ---------------------- a1 == a2 ---------------------- 
type:  <class 'numpy.ndarray'>
[[False False  True]
 [False False False]] 

