In [1]:
from typing import TypeVar


T = TypeVar('T')

def pr(val : T , title:str|None = None) : # type: ignore
    if title != None :
        print(f" ---------------------- {title} ---------------------- ")
    print('type: ' , type(val))
    print(val , '\n')
    # return val


In [2]:
import numpy as np # type: ignore
import numpy.typing as npt # type: ignore
import pandas as pd # type: ignore

In [6]:
a1:npt.NDArray[np.int64] = np.random.randint(10,20 , (3,5))
pr(a1 , 'a1')
pr(np.sort(a1) , 'np.sort(a1)')
# .sort method on a numpy array mutate the original numpy array
a1.sort()
pr(a1 , 'a1.sort()')


 ---------------------- a1 ---------------------- 
type:  <class 'numpy.ndarray'>
[[15 10 19 17 19]
 [14 15 17 16 10]
 [10 18 13 14 13]] 

 ---------------------- np.sort(a1) ---------------------- 
type:  <class 'numpy.ndarray'>
[[10 15 17 19 19]
 [10 14 15 16 17]
 [10 13 13 14 18]] 

 ---------------------- a1.sort() ---------------------- 
type:  <class 'numpy.ndarray'>
[[10 15 17 19 19]
 [10 14 15 16 17]
 [10 13 13 14 18]] 



In [ ]:
a1:npt.NDArray[np.int64] = np.random.randint(10,20 , (3,5))
pr(a1 , 'a1')
pr(np.argsort(a1) , 'np.argsort(a1)')
# both methods argmin and argmax are very confusing because i used to axis=0 is for the rows and axis-1 is for the columns.
# but when i used axis=0 the result has size(5) and when i used axis=1 the result has size(3)
# it should be reversed in my opinion.
pr(np.argmin(a1 , axis=0) , 'np.argmin(a1 , axis=0)')
pr(np.argmin(a1 , axis=1) , 'np.argmin(a1 , axis=1)')
pr(np.argmax(a1 , axis=0) , 'np.argmax(a1 , axis=0)')
pr(np.argmax(a1 , axis=1) , 'np.argmax(a1 , axis=1)')

 ---------------------- a1 ---------------------- 
type:  <class 'numpy.ndarray'>
[[18 13 13 19 11]
 [16 16 15 16 16]
 [11 12 12 19 15]] 

 ---------------------- np.argsort(a1) ---------------------- 
type:  <class 'numpy.ndarray'>
[[4 1 2 0 3]
 [2 0 1 3 4]
 [0 1 2 4 3]] 

 ---------------------- np.argmin(a1 , axis=0) ---------------------- 
type:  <class 'numpy.ndarray'>
[2 2 2 1 0] 

 ---------------------- np.argmin(a1 , axis=1) ---------------------- 
type:  <class 'numpy.ndarray'>
[4 2 0] 

 ---------------------- np.argmax(a1 , axis=0) ---------------------- 
type:  <class 'numpy.ndarray'>
[0 1 1 0 1] 

 ---------------------- np.argmax(a1 , axis=1) ---------------------- 
type:  <class 'numpy.ndarray'>
[3 0 3] 

